name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le déploiement à chaque push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilise le jeton d'accès par défaut de GitHub
          publish_dir: ./veille\ cv\ html\ css  # Spécifie le répertoire à déployer
          publish_branch: gh-pages  # Spécifie la branche de déploiement
